version: '3.7'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - redisnet
    command: ["redis-server", "--requirepass", "123123", "--user", "pick", "on"]

networks:
  redisnet:
    driver: bridge
