server.port: 8081
spring:
  application:
    name: webflux-database-base
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:5432/test
    username: postgres
    password: 123456
  data:
    redis:
      host: "localhost"
      port: 6379
      database: 0
      username: "pick"
      password: "123123"